-- MySQL Script generated by MySQL Workbench
-- Tue Feb 27 19:38:17 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `nif` INT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`E-E`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`E-E` (
  `departamtento` INT NOT NULL,
  `EMPLEADO_nifesresponsable` INT NULL,
  `EMPLEADO_nif1tienecomoresponsable` INT NOT NULL,
  PRIMARY KEY (`EMPLEADO_nifesresponsable`, `EMPLEADO_nif1tienecomoresponsable`),
  INDEX `fk_E-E_EMPLEADO1_idx` (`EMPLEADO_nif1tienecomoresponsable` ASC) VISIBLE,
  CONSTRAINT `fk_E-E_EMPLEADO`
    FOREIGN KEY (`EMPLEADO_nifesresponsable`)
    REFERENCES `mydb`.`EMPLEADO` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_E-E_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_nif1tienecomoresponsable`)
    REFERENCES `mydb`.`EMPLEADO` (`nif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
